#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.5 on Mon Mar  1 23:25:47 2021
#

import wx
import wx.adv

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade
from utils import resource_path


class SpoofyLoginDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SpoofyLoginDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((400, 400))
        self.title = wx.StaticText(self, wx.ID_ANY, "Spoofy Client v0.1", style=wx.ALIGN_CENTER)
        self.username = wx.TextCtrl(self, wx.ID_ANY, "")
        self.password = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.bitrate = wx.Choice(self, wx.ID_ANY, choices=["96 kbps", "160 kbps", "320 kbps"])
        self.login_button = wx.Button(self, wx.ID_ANY, "Log in")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: SpoofyLoginDialog.__set_properties
        self.SetTitle("Spoofy Client - Login")
        self.SetSize((400, 400))
        self.title.SetFont(wx.Font(16, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        self.bitrate.SetSelection(1)
        self.login_button.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: SpoofyLoginDialog.__do_layout
        sizer_container = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_form = wx.FlexGridSizer(3, 2, 4, 4)
        spoofy_logo = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap(resource_path("res/spoofy_small.png"), wx.BITMAP_TYPE_ANY), style=wx.FULL_REPAINT_ON_RESIZE)
        spoofy_logo.SetMinSize((128, 128))
        sizer_container.Add(spoofy_logo, 0, wx.ALIGN_CENTER | wx.LEFT | wx.RIGHT | wx.TOP, 8)
        sizer_container.Add(self.title, 0, wx.ALIGN_CENTER | wx.ALL, 4)
        description = wx.StaticText(self, wx.ID_ANY, "To start using the bot, please log in to your Spotify account.")
        sizer_container.Add(description, 0, wx.ALIGN_CENTER | wx.BOTTOM | wx.LEFT | wx.RIGHT, 4)
        username_label = wx.StaticText(self, wx.ID_ANY, "Spotify username:", style=wx.ALIGN_RIGHT)
        grid_sizer_form.Add(username_label, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_form.Add(self.username, 0, wx.EXPAND, 0)
        password_label = wx.StaticText(self, wx.ID_ANY, "Spotify password:", style=wx.ALIGN_RIGHT)
        grid_sizer_form.Add(password_label, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_form.Add(self.password, 0, wx.EXPAND, 0)
        bitrate_label = wx.StaticText(self, wx.ID_ANY, "Bitrate:", style=wx.ALIGN_RIGHT)
        grid_sizer_form.Add(bitrate_label, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_form.Add(self.bitrate, 0, wx.ALL | wx.EXPAND, 0)
        grid_sizer_form.AddGrowableCol(1)
        sizer_container.Add(grid_sizer_form, 0, wx.ALL | wx.EXPAND, 8)
        sizer_container.Add(self.login_button, 0, wx.ALL | wx.EXPAND, 8)
        self.SetSizer(sizer_container)
        self.Layout()
        # end wxGlade

# end of class SpoofyLoginDialog

class SpoofyStatusDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SpoofyStatusDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((500, 500))
        self.exit_button = wx.Button(self, wx.ID_ANY, "Exit")
        self.log_out_button = wx.Button(self, wx.ID_ANY, "Log out")
        self.minimize_button = wx.Button(self, wx.ID_ANY, "Minimize to tray")
        self.about_button = wx.Button(self, wx.ID_ANY, "About")
        self.label_description = wx.StaticText(self, wx.ID_ANY, "Enter a link code from the bot (s!join) and click Connect to start playing music.")
        self.link_code = wx.TextCtrl(self, wx.ID_ANY, "")
        self.connect_button = wx.Button(self, wx.ID_ANY, "Connect")
        self.status_spotify_icon = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap(resource_path("res/060-warning.png"), wx.BITMAP_TYPE_ANY))
        self.status_spotify_label = wx.StaticText(self, wx.ID_ANY, "Spotify: Unknown")
        self.status_bot_icon = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap(resource_path("res/060-warning.png"), wx.BITMAP_TYPE_ANY))
        self.status_bot_label = wx.StaticText(self, wx.ID_ANY, "Spoofy Bot: Unknown")
        self.log_text = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE | wx.TE_PROCESS_ENTER | wx.TE_READONLY | wx.TE_WORDWRAP)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: SpoofyStatusDialog.__set_properties
        self.SetTitle("Spoofy Client - Status")
        self.SetSize((500, 500))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: SpoofyStatusDialog.__do_layout
        sizer_container = wx.BoxSizer(wx.VERTICAL)
        sizer_log = wx.BoxSizer(wx.VERTICAL)
        sizer_status = wx.BoxSizer(wx.VERTICAL)
        status_grid = wx.FlexGridSizer(2, 2, 6, 6)
        sizer_controls = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_link_code = wx.FlexGridSizer(1, 3, 4, 4)
        grid_sizer_control_buttons = wx.GridSizer(2, 2, 4, 4)
        label_controls = wx.StaticText(self, wx.ID_ANY, "Controls")
        label_controls.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_controls.Add(label_controls, 0, wx.LEFT | wx.RIGHT | wx.TOP, 4)
        grid_sizer_control_buttons.Add(self.exit_button, 1, wx.EXPAND, 0)
        grid_sizer_control_buttons.Add(self.log_out_button, 1, wx.EXPAND, 0)
        grid_sizer_control_buttons.Add(self.minimize_button, 1, wx.EXPAND, 0)
        grid_sizer_control_buttons.Add(self.about_button, 1, wx.EXPAND, 0)
        sizer_controls.Add(grid_sizer_control_buttons, 0, wx.ALL | wx.EXPAND, 8)
        sizer_controls.Add(self.label_description, 0, wx.EXPAND | wx.LEFT | wx.RIGHT, 8)
        label_link_code = wx.StaticText(self, wx.ID_ANY, "Link code:")
        grid_sizer_link_code.Add(label_link_code, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_link_code.Add(self.link_code, 0, wx.EXPAND, 0)
        grid_sizer_link_code.Add(self.connect_button, 0, 0, 0)
        grid_sizer_link_code.AddGrowableCol(1)
        sizer_controls.Add(grid_sizer_link_code, 0, wx.ALL | wx.EXPAND, 8)
        sizer_container.Add(sizer_controls, 0, wx.EXPAND, 0)
        label_status = wx.StaticText(self, wx.ID_ANY, "Status")
        label_status.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_status.Add(label_status, 0, wx.LEFT | wx.RIGHT | wx.TOP, 4)
        status_grid.Add(self.status_spotify_icon, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        status_grid.Add(self.status_spotify_label, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        status_grid.Add(self.status_bot_icon, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        status_grid.Add(self.status_bot_label, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        status_grid.AddGrowableCol(1)
        sizer_status.Add(status_grid, 0, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 8)
        sizer_container.Add(sizer_status, 0, wx.EXPAND, 0)
        label_log = wx.StaticText(self, wx.ID_ANY, "Log output (most recent on top)")
        label_log.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_log.Add(label_log, 0, wx.LEFT | wx.RIGHT, 4)
        sizer_log.Add(self.log_text, 1, wx.ALL | wx.EXPAND, 2)
        sizer_container.Add(sizer_log, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_container)
        self.Layout()
        # end wxGlade

# end of class SpoofyStatusDialog

class AboutDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: AboutDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((400, 415))
        self.title = wx.StaticText(self, wx.ID_ANY, "Spoofy Client v0.1", style=wx.ALIGN_CENTER)
        self.label_version_current = wx.StaticText(self, wx.ID_ANY, "Current version: v0.1")
        self.label_version_latest = wx.StaticText(self, wx.ID_ANY, "Latest version: Unknown")
        self.link_client = wx.adv.HyperlinkCtrl(self, wx.ID_ANY, "https://github.com/Kanakonn/SpoofyClient", "https://github.com/Kanakonn/SpoofyClient", style=wx.adv.HL_ALIGN_LEFT)
        self.link_bot = wx.adv.HyperlinkCtrl(self, wx.ID_ANY, "https://github.com/Kanakonn/Spoofy", "https://github.com/Kanakonn/Spoofy", style=wx.adv.HL_ALIGN_LEFT)
        self.close_button = wx.Button(self, wx.ID_CLOSE, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: AboutDialog.__set_properties
        self.SetTitle("Spoofy Client - About")
        self.SetSize((400, 415))
        self.title.SetFont(wx.Font(16, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: AboutDialog.__do_layout
        sizer_container = wx.BoxSizer(wx.VERTICAL)
        spoofy_logo = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap(resource_path("res/spoofy_small.png"), wx.BITMAP_TYPE_ANY), style=wx.FULL_REPAINT_ON_RESIZE)
        spoofy_logo.SetMinSize((128, 128))
        sizer_container.Add(spoofy_logo, 0, wx.ALIGN_CENTER | wx.LEFT | wx.RIGHT | wx.TOP, 8)
        sizer_container.Add(self.title, 0, wx.ALIGN_CENTER | wx.LEFT | wx.RIGHT | wx.TOP, 12)
        about = wx.StaticText(self, wx.ID_ANY, "This is the client application belonging to the Spoofy Discord bot. Find more information about the bot on it's GitHub page linked below.")
        sizer_container.Add(about, 1, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 8)
        sizer_container.Add(self.label_version_current, 0, wx.LEFT | wx.RIGHT, 8)
        sizer_container.Add(self.label_version_latest, 0, wx.LEFT | wx.RIGHT, 8)
        sizer_container.Add(self.link_client, 0, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 8)
        sizer_container.Add(self.link_bot, 0, wx.EXPAND | wx.LEFT | wx.RIGHT, 8)
        sizer_container.Add(self.close_button, 0, wx.ALIGN_RIGHT | wx.ALL, 8)
        self.SetSizer(sizer_container)
        self.Layout()
        # end wxGlade

# end of class AboutDialog

class SpoofyClientApp(wx.App):
    def OnInit(self):
        self.status_dialog = SpoofyStatusDialog(None, wx.ID_ANY, "")
        self.SetTopWindow(self.status_dialog)
        self.status_dialog.ShowModal()
        self.status_dialog.Destroy()
        return True

# end of class SpoofyClientApp

if __name__ == "__main__":
    spoofy_client = SpoofyClientApp(0)
    spoofy_client.MainLoop()
